disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sasquatch's Place"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
   logo = "img/logo.png"
#   secondaryLogo = "img/logo.png"
   description = "The personal blog of Sasquatch"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Gregory Lopez"
#   email = "blindsquatch@4d2.org"
   image = "img/author.jpg"
   imageQuality = 96
   headline = "Gregarious By Design"
#   bio = ""
   links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
     { bluesky = "https://bsky.app/profile/thesneakysquatch.bsky.social" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.com/users/877529484083998751" },
#     { dribbble = "https://dribbble.com/username" },
     { facebook = "https://facebook.com/thesneakysquatch" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/thesneakysquatch" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/thesneakysquatch" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
     { mastodon = "https://4d2.social/@sasquatch" },
     { matrix = "https://matrix.to/#/@blindsquatch:4d2.org" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
     { peertube = "https://video.4d2.org/c/squatchvids" },
#     { pinterest = "https://pinterest.com/username" },
     { reddit = "https://reddit.com/user/thesneakysquatch" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/thesneakysquatch" },
     { threads = "https://www.threads.net/@thesneakysquatch" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/+12064882148" },
#     { youtube = "https://youtube.com/@thesneakysquatch" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]